apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  annotations:
    appconnect.ibm.com/hibernate: 'false'
  name: ace-ping-application-cp4i
  namespace: cp4i
spec:
  flowType:
    toolkitFlow: true
  license:
    accept: true
    license: L-APEH-CJUCNR
    use: AppConnectEnterpriseNonProductionFREE
  template:
    spec:
      containers:
        - image: >-
            quay.io/trevor_dolby/ace-ping-application-cp4i:latest
          imagePullPolicy: Always
          name: runtime
          resources:
            requests:
              cpu: 300m
              memory: 368Mi
#  configurations:
#    - max-keep-alive-requests
  version: 12.0.7.0-r3
